version: 0.0
os: linux
files:
  - source: target/SpringMVCHibernateCRUD.war
    destination: /opt/codedeploy/
  - source: /scripts/configure_http_port.xsl
    destination: /opt/codedeploy/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 400
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 400
  ApplicationStart:
    - location: scripts/start_application
      timeout: 400
